### ISSUE TITLE
Change cocoon's `unwrap` and `wrap` method names to avoid ambiguity

### ISSUE THREAD

**Issue by dark-fusion** [fadeevab/cocoon#15]
As you're likely aware, Rust's core library contains an `unwrap` method that can be used on all `Option` and `Result` types. This makes reading code using this crate difficult for no real good reason.

I really love your work and I'm planning on using it. Replacing cocoon's `unwrap` and `wrap` methods could be done with a simple refactor step and subsequent find-and-replace action. This would eliminate confusion regarding the Rust core method and Cocoon's.

**Comment by fadeevab** [comment]
@dark-fusion Thank you for you comment and overall appreciate your feedback! It won't be so easy to rename them because of backward compatibility: someone depends on the crate, and changing the API will break the builds. Also, it actually means something similar as a concept: wrapping to a container (to a "cocoon") and unwrapping from it.

**Comment by dark-fusion** [comment]
Thank you for the thoughtful (and complete) explanation. You make some very good points, especially RE: backward compatibility.

I think the following is quite true:
> "...it actually means something similar as a concept: wrapping to a container (to a "cocoon") and unwrapping from it."

Although `unwrap` from the std lib can/will panic, it's use is largely discouraged in production code, ergo there should be little to no confusion in an actual project.

Closing this issue as I consider it solved. Thanks!
